### ISSUE TITLE
InputfieldMarkup.description does not render description in PW 2.8

### ISSUE THREAD

**Issue by owzim** [kongondo/Blog#24]
Unfortunately, in PW 2.8 the description field is entity-encoded, see `InputfielMarkup.module` around `line 59`:

``` php
if($description) {
    $description = $this->entityEncode($description, Inputfield::textFormatBasic);
    $out = "\n<p class='description'>{$description}</p>" . $out;
    $this->description = ''; // prevents it from appearing again at the bottom
}
```

So this is the result on any description field in on the dashboard:

![screen shot 2016-07-09 at 13 14 35](https://cloud.githubusercontent.com/assets/1720088/16707670/1c0e5d78-45d7-11e6-9cd9-5ac7a320ff07.png)

**Comment by kongondo** [comment]
Thanks @owzim, will look into this

**Comment by kongondo** [comment]
Thanks @owzim. This now sorted out as per this commit (ba1412f2ff36a11fee191fae046ccee43259e4fc).
