### ISSUE TITLE
Fancybox dropped in PW 2.8, dashboard stops to work

### ISSUE THREAD

**Issue by owzim** [kongondo/Blog#25]
Fancybox is dropped from the core, so manually installing it will do the trick, but out of the box it won't work.

**Comment by kongondo** [comment]
Thanks for this @owzim. Will be switching to magnific.

**Comment by kongondo** [comment]
Thanks @owzim. This now sorted out as per this commit (ba1412f2ff36a11fee191fae046ccee43259e4fc).
