### ISSUE TITLE
Not working with multi-languages

### ISSUE THREAD

**Issue by q2apro** [kongondo/Blog#29]
Have installed the "LanguageSupport" modules and the ProcessBlog module.

I see the second language as a field "German": 

![capture](https://cloud.githubusercontent.com/assets/6764548/17815190/e26e666e-663b-11e6-939b-518b97eb2ac3.PNG)

but when clicking it, it does not show the other editor for this language, still the same editor for English. 

Could this be fixed?

**Comment by kongondo** [comment]
Sorry I missed this issue and it dragged on for too long. I have not been able to reproduce this nor heard of any similar reports. Is this still an issue? Thanks.
