### ISSUE TITLE
little phpdoc typo

### ISSUE THREAD

**Issue by CanRau** [kongondo/Blog#33]
https://github.com/kongondo/Blog/blob/master/ProcessBlog.module#L761
second last word should read Blog instead of Blod..I guess?! ;-)

**Comment by kongondo** [comment]
Hehe. Definitely. Good catch...Will sort out in next version, along with other changes. Thanks.

**Comment by CanRau** [comment]
you're welcome ;-)

just checked out one of the videos demonstrating process blog..nice work! and nice ideas..really like the quick add article!
