### ISSUE TITLE
.post-head element not rendered inside .post

### ISSUE THREAD

**Issue by dhansmair** [kongondo/Blog#36]
The renderPosts() method actually renders the div.post-head element before div.post and not inside, contrary to the API specification on http://blog.kongondo.com/documentation/blog-api/render-posts/

I assume this line should be executed earlier:
https://github.com/kongondo/Blog/blob/ec518bcc1dad343f2151f484a11f694ac4809c25/MarkupBlog.module#L939

**Comment by kongondo** [comment]
Thanks for reporting @dhansmair. I'll fix this in the next update.

**Comment by kongondo** [comment]
@dhansmair. I have had a look and I see no issues here. div.post-head element is rendered inside div.post. Maybe if you could show me your markup blog settings to have a look? Closing this for now, but please reopen if you need to. Thanks.
