### ISSUE TITLE
Removing blog_tags field from blog-post template causes Fatal Errors in admin

### ISSUE THREAD

**Issue by prestoav** [kongondo/Blog#37]
V 2.4.5

Please see full issue here: https://processwire.com/talk/topic/25211-solved-error-after-upgrade-blog-module-240-to-245/

If the blog_tag is removed from the template in PW then fatal errors occur when trying to access Blog > Posts in Blog module admin. Errors not present in 2.4.0.

**Comment by kongondo** [comment]
Hi @prestoav. I do not consider this a bug. blog_tags is a required field for blog-post and is installed with it. I am closing this. Thanks.
