### ISSUE TITLE
ProcessBlog: Can’t save page 0: /blog-author: It has no parent assigned

### ISSUE THREAD

**Issue by saschanos** [kongondo/Blog#38]
Running the installer causes the following error. I am using MultiLanguage modules.

`DEBUG MODE BACKTRACE ($config->debug == true):
#0 /Users/XXX/htdocs/vendor/processwire/processwire/wire/core/Pages.php(799): ProcessWire\PagesEditor->save(Object(ProcessWire\Role), Array)
#1 /Users/XXX/htdocs/vendor/processwire/processwire/wire/core/Wire.php(420): ProcessWire\Pages->___save(Object(ProcessWire\Role), Array)
#2 /Users/XXX/htdocs/vendor/processwire/processwire/wire/core/WireHooks.php(951): ProcessWire\Wire->_callMethod('___save', Array)
#3 /Users/XXX/htdocs/vendor/processwire/processwire/wire/core/Wire.php(485): ProcessWire\WireHooks->runHooks(Object(ProcessWire\Pages), 'save', Array)
#4 /Users/XXX/htdocs/vendor/processwire/processwire/wire/core/Page.php(2774): ProcessWire\Wire->__call('save', Array)
#5 /Users/XXX/htdocs/public/site/modules/MarkupBlog/BlogInstallWizard.php(324): ProcessWire\Page->save()
#6 /Users/XXX/htdocs/public/site/modules/MarkupBlog/BlogInstallWizard.php(304): ProcessWire\BlogInstallWizard->createRole()
#7 /Users/XXX/htdocs/public/site/modules/MarkupBlog/ProcessBlog.module(3335): ProcessWire\BlogInstallWizard->verifyInstall(Object(ProcessWire\InputfieldForm))
#8 /Users/XXX/htdocs/public/site/modules/MarkupBlog/ProcessBlog.module(778): ProcessWire\ProcessBlog->installWizard(Object(ProcessWire\InputfieldForm))
#9 /Users/XXX/htdocs/public/site/modules/MarkupBlog/ProcessBlog.module(1945): ProcessWire\ProcessBlog->renderFirstAccess(Array)
#10 /Users/XXX/htdocs/vendor/processwire/processwire/wire/core/ProcessController.php(337): ProcessWire\ProcessBlog->execute()
#11 /Users/XXX/htdocs/vendor/processwire/processwire/wire/core/Wire.php(414): ProcessWire\ProcessController->___execute()
#12 /Users/XXX/htdocs/vendor/processwire/processwire/wire/core/WireHooks.php(951): ProcessWire\Wire->_callMethod('___execute', Array)
#13 /Users/XXX/htdocs/vendor/processwire/processwire/wire/core/Wire.php(485): ProcessWire\WireHooks->runHooks(Object(ProcessWire\ProcessController), 'execute', Array)
#14 /Users/XXX/htdocs/vendor/processwire/processwire/wire/core/admin.php(160): ProcessWire\Wire->__call('execute', Array)
#15 /Users/XXX/htdocs/vendor/processwire/processwire/wire/modules/AdminTheme/AdminThemeUikit/controller.php(15): require('/Users/sascha/P...')
#16 /Users/XXX/htdocs/public/site/templates/admin.php(15): require('/Users/sascha/P...')
#17 /Users/XXX/htdocs/vendor/processwire/processwire/wire/core/TemplateFile.php(327): require('/Users/sascha/P...')
#18 /Users/XXX/htdocs/vendor/processwire/processwire/wire/core/Wire.php(414): ProcessWire\TemplateFile->___render()
#19 /Users/XXX/htdocs/vendor/processwire/processwire/wire/core/WireHooks.php(951): ProcessWire\Wire->_callMethod('___render', Array)
#20 /Users/XXX/htdocs/vendor/processwire/processwire/wire/core/Wire.php(485): ProcessWire\WireHooks->runHooks(Object(ProcessWire\TemplateFile), 'render', Array)
#21 /Users/XXX/htdocs/vendor/processwire/processwire/wire/modules/PageRender.module(553): ProcessWire\Wire->__call('render', Array)
#22 /Users/XXX/htdocs/vendor/processwire/processwire/wire/core/Wire.php(417): ProcessWire\PageRender->___renderPage(Object(ProcessWire\HookEvent))
#23 /Users/XXX/htdocs/vendor/processwire/processwire/wire/core/WireHooks.php(951): ProcessWire\Wire->_callMethod('___renderPage', Array)
#24 /Users/XXX/htdocs/vendor/processwire/processwire/wire/core/Wire.php(485): ProcessWire\WireHooks->runHooks(Object(ProcessWire\PageRender), 'renderPage', Array)
#25 /Users/XXX/htdocs/vendor/processwire/processwire/wire/core/WireHooks.php(1059): ProcessWire\Wire->__call('renderPage', Array)
#26 /Users/XXX/htdocs/vendor/processwire/processwire/wire/core/Wire.php(485): ProcessWire\WireHooks->runHooks(Object(ProcessWire\Page), 'render', Array)
#27 /Users/XXX/htdocs/vendor/processwire/processwire/wire/modules/Process/ProcessPageView.module(225): ProcessWire\Wire->__call('render', Array)
#28 /Users/XXX/htdocs/vendor/processwire/processwire/wire/modules/Process/ProcessPageView.module(171): ProcessWire\ProcessPageView->renderPage(Object(ProcessWire\Page))
#29 /Users/XXX/htdocs/vendor/processwire/processwire/wire/core/Wire.php(417): ProcessWire\ProcessPageView->___execute(true)
#30 /Users/XXX/htdocs/vendor/processwire/processwire/wire/core/WireHooks.php(951): ProcessWire\Wire->_callMethod('___execute', Array)
#31 /Users/XXX/htdocs/vendor/processwire/processwire/wire/core/Wire.php(485): ProcessWire\WireHooks->runHooks(Object(ProcessWire\ProcessPageView), 'execute', Array)
#32 /Users/XXX/htdocs/public/index.php(55): ProcessWire\Wire->__call('execute', Array)`

**Comment by kongondo** [comment]
Sorry that this has been open for so long @saschanos. This is now fixed in a13af30. Please test and let me know, thanks. I'll close this one but feel free to reopen if you still experience issues.
