### ISSUE TITLE
v2.01 Default templates/markup not checking if comments should exist

### ISSUE THREAD

**Issue by DBPreston** [kongondo/Blog#8]
I'm getting the following error 'Error: Class 'Comment' not found (line 509 of D:\wamp\www\dpb\site\modules\ProcessBlog\MarkupBlog.module)', probably because I chose the option of not installing Comments with the blog (intending to use Disqus instead).

**Comment by gebeer** [comment]
I am getting the same error:
Error: Class 'Comment' not found (line 599 of .../site/modules/ProcessBlog/MarkupBlog.module)

thats why I'm not opening a new issue.

It happens on a clean install of 3.0.42 with the intermediate site profile. I installed Blog module with comments and everything except for scheduled pages. All template/field names are default.
The error message appears in the sidebar where the comments would be rendered.
![2016-12-04 11 04 54](https://cloud.githubusercontent.com/assets/3088950/20864000/96cad74a-ba11-11e6-86f0-e0019fb747c2.png)

Could this be a namespacing issue?

**Comment by kongondo** [comment]
I haven't been able to reproduce. I've tested in same version of ProcessWire (blank profile though). Please confirm you have FieldtypeComments installed (you should, but just confirming). Also clearing cache several times? We've been seeing the error in ProcessWire 3 (namespace) but fixed the bug by loading FieldtypeComments when the module is initialised.
